### ISSUE TITLE
Internal error

### ISSUE THREAD

**Issue by kevthehermit** [rekall-innovations/rekall-agent-server#1]
Tried to deploy this to gcloud following the steps in http://dfrws2017.rekall-forensic.com/Rekall%20Workshop.pdf

I get an error in the browser
```
Internal error

Ticket issued: unknown
```

When i try to deploy on a local server using dev_appserver i get the same error and this traceback

```
localadmin@rekall:~/rekall-agent-server$ dev_appserver.py --host 0.0.0.0 app.yaml 
INFO     2017-11-01 14:39:41,777 devappserver2.py:105] Skipping SDK update check.
INFO     2017-11-01 14:39:42,044 api_server.py:300] Starting API server at: http://localhost:39154
INFO     2017-11-01 14:39:42,085 dispatcher.py:251] Starting module "default" running at: http://0.0.0.0:8080
INFO     2017-11-01 14:39:42,086 admin_server.py:116] Starting admin server at: http://localhost:8000
INFO     2017-11-01 14:39:45,397 driver.py:120] Generating grammar tables from /usr/lib/python2.7/lib2to3/Grammar.txt
INFO     2017-11-01 14:39:45,501 driver.py:120] Generating grammar tables from /usr/lib/python2.7/lib2to3/PatternGrammar.txt
ERROR    2017-11-01 14:39:45,882 restricted.py:172] Traceback (most recent call last):
  File "/home/localadmin/rekall-agent-server/gluon/restricted.py", line 217, in restricted
    exec(ccode, environment)
  File "/home/localadmin/rekall-agent-server/applications/Rekall/models/db.py", line 13, in <module>
    from api import dal
  File "/home/localadmin/rekall-agent-server/gluon/custom_import.py", line 104, in custom_importer
    raise ImportError(e1, import_tb)  # there an import error in the module
ImportError: (ImportError(ImportError(ImportError('No module named rekall_lib.types',), <traceback object at 0x7fbafd0a95f0>), <traceback object at 0x7fbafd0a9488>), <traceback object at 0x7fbafcd38710>)

INFO     2017-11-01 14:39:45,883 gaehandler.py:75] **** Request: 582.51ms/576.07ms (real time/cpu time)
INFO     2017-11-01 14:39:45,893 module.py:821] default: "GET / HTTP/1.1" 500 707
INFO     2017-11-01 14:39:46,112 module.py:821] default: "GET /favicon.ico HTTP/1.1" 200 19086
```

**Comment by kevthehermit** [comment]
![appengine](https://user-images.githubusercontent.com/2545096/32281333-74ee7ed2-bf16-11e7-91d7-b8912ec15e8e.png)

**Comment by scudette** [comment]
Did you run the bootstrap script first? It should install dependencies into
the source tree before you upload the app.

**Comment by kevthehermit** [comment]
Yeah. Followed exactly. 
It looks like at some point rekall_lib.types became rekall_lib.rekall_types

https://github.com/rekall-innovations/rekall/commit/30cb30b14022924055618df330429791a0173478

**Comment by kevthehermit** [comment]
Replacing all the rekall_lib.types with rekall_lib.rekall_types seems to have worked so far. I can login at least

**Comment by scudette** [comment]
Ah sorry,
   I think I fixed this in a local branch and forgot to push upstream.
Thanks for reporting :-).

Thanks
Michael.

**Comment by kevthehermit** [comment]
Latest pull seems to be working now :)
