### ISSUE TITLE
Dev Local Server issue 

### ISSUE THREAD

**Issue by prats84** [rekall-innovations/rekall-agent-server#13]
Attempt to run development on Local server (Ubuntu 16.04) with
`dev_appserver.py . ` & getting the below Traceback when attempted to access localhost:8080 : 

INFO     2018-01-29 04:51:34,700 devappserver2.py:105] Skipping SDK update check.
INFO     2018-01-29 04:51:34,726 api_server.py:308] Starting API server at: http://localhost:42304
INFO     2018-01-29 04:51:34,748 dispatcher.py:255] Starting module "default" running at: http://0.0.0.0:8080
INFO     2018-01-29 04:51:34,748 admin_server.py:146] Starting admin server at: http://localhost:8000

 File "/home/ubuntu/rekall-agent-server/gluon/custom_import.py", line 99, in custom_importer
    return base_importer(pname, globals, locals, fromlist, level)
  File "/home/ubuntu/rekall-agent-server/gluon/custom_import.py", line 93, in custom_importer
    raise ImportError('Cannot import module %s' % str(e))
  File "/home/ubuntu/rekall-agent-server/gluon/custom_import.py", line 93, in custom_importer
    raise ImportError('Cannot import module %s' % str(e))
  File "/home/ubuntu/rekall-agent-server/gluon/custom_import.py", line 93, in custom_importer
    raise ImportError('Cannot import module %s' % str(e))
  File "/home/ubuntu/rekall-agent-server/gluon/custom_import.py", line 93, in custom_importer
    raise ImportError('Cannot import module %s' % str(e))
  File "/home/ubuntu/rekall-agent-server/gluon/custom_import.py", line 93, in custom_importer
    raise ImportError('Cannot import module %s' % str(e))
  File "/home/ubuntu/rekall-agent-server/gluon/custom_import.py", line 93, in custom_importer
    raise ImportError('Cannot import module %s' % str(e))
  File "/home/ubuntu/rekall-agent-server/gluon/custom_import.py", line 99, in custom_importer
    return base_importer(pname, globals, locals, fromlist, level)
  File "/home/ubuntu/rekall-agent-server/gluon/custom_import.py", line 99, in custom_importer
    return base_importer(pname, globals, locals, fromlist, level)
  File "/home/ubuntu/rekall-agent-server/gluon/custom_import.py", line 99, in custom_importer
    return base_importer(pname, globals, locals, fromlist, level)
  File "/home/ubuntu/rekall-agent-server/gluon/custom_import.py", line 93, in custom_importer
    raise ImportError('Cannot import module %s' % str(e))
  File "/home/ubuntu/rekall-agent-server/gluon/custom_import.py", line 99, in custom_importer
    return base_importer(pname, globals, locals, fromlist, level)
  File "/home/ubuntu/rekall-agent-server/gluon/custom_import.py", line 99, in custom_importer
    return base_importer(pname, globals, locals, fromlist, level)
  File "/home/ubuntu/rekall-agent-server/gluon/custom_import.py", line 93, in custom_importer
    raise ImportError('Cannot import module %s' % str(e))
  File "/home/ubuntu/rekall-agent-server/gluon/custom_import.py", line 99, in custom_importer
    return base_importer(pname, globals, locals, fromlist, level)
  File "/home/ubuntu/rekall-agent-server/gluon/custom_import.py", line 99, in custom_importer
    return base_importer(pname, globals, locals, fromlist, level)
  File "/home/ubuntu/rekall-agent-server/gluon/custom_import.py", line 99, in custom_importer
    return base_importer(pname, globals, locals, fromlist, level)
  File "/home/ubuntu/rekall-agent-server/gluon/custom_import.py", line 99, in custom_importer
    return base_importer(pname, globals, locals, fromlist, level)
  File "/home/ubuntu/rekall-agent-server/gluon/custom_import.py", line 99, in custom_importer
    return base_importer(pname, globals, locals, fromlist, level)
  File "/home/ubuntu/rekall-agent-server/gluon/custom_import.py", line 99, in custom_importer
    return base_importer(pname, globals, locals, fromlist, level)
  File "/home/ubuntu/rekall-agent-server/gluon/custom_import.py", line 99, in custom_importer
    return base_importer(pname, globals, locals, fromlist, level)
  File "/home/ubuntu/rekall-agent-server/gluon/custom_import.py", line 99, in custom_importer
    return base_importer(pname, globals, locals, fromlist, level)
  File "/home/ubuntu/rekall-agent-server/gluon/custom_import.py", line 99, in custom_importer
    return base_importer(pname, globals, locals, fromlist, level)
  File "/home/ubuntu/rekall-agent-server/gluon/custom_import.py", line 99, in custom_importer
    return base_importer(pname, globals, locals, fromlist, level)
  File "/home/ubuntu/rekall-agent-server/gluon/custom_import.py", line 99, in custom_importer
    return base_importer(pname, globals, locals, fromlist, level)
  File "/home/ubuntu/rekall-agent-server/gluon/custom_import.py", line 99, in custom_importer
    return base_importer(pname, globals, locals, fromlist, level)
  File "applications/Rekall/modules/api/audit.py", line 3, in <module>
    from rekall_lib import serializer
  File "/home/ubuntu/rekall-agent-server/gluon/custom_import.py", line 106, in custom_importer
    raise ImportError(e1, import_tb)  # there an import error in the module
  File "/home/ubuntu/rekall-agent-server/gluon/custom_import.py", line 99, in custom_importer
    return base_importer(pname, globals, locals, fromlist, level)
  File "applications/Rekall/modules/api/__init__.py", line 11, in <module>
    from api import audit
  File "/home/ubuntu/rekall-agent-server/gluon/custom_import.py", line 99, in custom_importer
    return base_importer(pname, globals, locals, fromlist, level)
  File "/home/ubuntu/rekall-agent-server/gluon/custom_import.py", line 106, in custom_importer
    raise ImportError(e1, import_tb)  # there an import error in the module
  File "/home/ubuntu/rekall-agent-server/gluon/custom_import.py", line 99, in custom_importer
    return base_importer(pname, globals, locals, fromlist, level)
  File "/home/ubuntu/rekall-agent-server/gluon/custom_import.py", line 99, in custom_importer
    return base_importer(pname, globals, locals, fromlist, level)
  File "/home/ubuntu/rekall-agent-server/gluon/custom_import.py", line 99, in custom_importer
    return base_importer(pname, globals, locals, fromlist, level)
  File "applications/Rekall/modules/api/audit.py", line 3, in <module>
    from rekall_lib import serializer
  File "/home/ubuntu/rekall-agent-server/gluon/custom_import.py", line 106, in custom_importer
    raise ImportError(e1, import_tb)  # there an import error in the module
  File "/home/ubuntu/rekall-agent-server/gluon/custom_import.py", line 99, in custom_importer
    return base_importer(pname, globals, locals, fromlist, level)
  File "applications/Rekall/modules/api/__init__.py", line 11, in <module>
    from api import audit
  File "/home/ubuntu/rekall-agent-server/gluon/custom_import.py", line 106, in custom_importer
    raise ImportError(e1, import_tb)  # there an import error in the module
ERROR    2018-01-29 04:44:35,096 restricted.py:172] Traceback (most recent call last):
  File "/home/ubuntu/rekall-agent-server/gluon/restricted.py", line 217, in restricted
    exec(ccode, environment)
  File "/home/ubuntu/rekall-agent-server/applications/Rekall/models/db.py", line 13, in <module>
    from api import dal
  File "/home/ubuntu/rekall-agent-server/gluon/custom_import.py", line 106, in custom_importer
    raise ImportError(e1, import_tb)  # there an import error in the module
ImportError: (ImportError(ImportError(ImportError('No module named rekall_lib',), <traceback object at 0x7faecae6e5f0>), <traceback object at 0x7faecae6e638>), <traceback object at 0x7faecb331e18>)

INFO     2018-01-29 04:44:35,096 gaehandler.py:75] **** Request: 491.26ms/676.07ms (real time/cpu time)
INFO     2018-01-29 04:44:35,103 module.py:835] default: "GET / HTTP/1.1" 500 707
ERROR    2018-01-29 04:44:35,117 restricted.py:172] Traceback (most recent call last):
  File "/home/ubuntu/rekall-agent-server/gluon/restricted.py", line 217, in restricted
    exec(ccode, environment)
  File "/home/ubuntu/rekall-agent-server/applications/Rekall/models/db.py", line 13, in <module>
    from api import dal
  File "/home/ubuntu/rekall-agent-server/gluon/custom_import.py", line 106, in custom_importer
    raise ImportError(e1, import_tb)  # there an import error in the module
ImportError: (ImportError(ImportError(ImportError('No module named rekall_lib',), <traceback object at 0x7faecae7f710>), <traceback object at 0x7faecae7f3b0>), <traceback object at 0x7faecae7f830>)
`

I have run bootstrap.sh prior to dev_appserver

**Comment by prats84** [comment]
Closing this out as pycrypto was missing
installed with pip install pycrypto

**Comment by scudette** [comment]
Yes, it was not included in the bootstrap.sh. Fixed by 4b580cc7e603c5836cfe149ea388b7640416ccbf
